spring:
  application:
    name: proxy
server:
  port: 8765
eureka:
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka
zuul:
  ignored-services: '*'
  strip-prefix: false
  routes:
    api-v1:
      path: /api/v1/**
    api-v2:
      path: /api/v2/**