spring:
  application:
    name: users
server:
  port: 0
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaulZone: http://localhost:8761/eureka
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}