eureka:
  instance:
    hostname: localhost
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/