server:
  port: 8888
eureka:
  instance:
    hostname: localhost
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka